# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c96108752ec96da805db2228ab7b0bfc55262f37448bb37f27763165fd0f9776de979d9fd6801e3352f707d37f6cb2af2ee724043d837d8bd20e132413e4f390

test:
  secret_key_base: 3bef97eca62f42f2e96f501db6230de38422cbc467a49a57d2900e14e28634ee4fa52bde57b00756ecb2f9310deff5fa058683d6bc5b86500a90d99ed42fba9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
